const { isPermutation } = require("../Strings_05");

describe("Determine if a string is a permutation of another", () => {
  it("Should compare every permutation of a string of length four", () => {
    let str1 = "abcd";
    let str2 = "abcd";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "abdc";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "adbc";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "adcb";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "acbd";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "acdb";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "bacd";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "badc";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "bcad";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "bcda";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "bdca";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "bdac";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "cabd";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "cadb";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "cbad";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "cbda";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "cdab";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "cdba";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "dabc";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "dacb";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "dbac";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "dbca";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "dcba";
    expect(isPermutation(str1, str2)).toBeTruthy();
    str2 = "dcab";
    expect(isPermutation(str1, str2)).toBeTruthy();
  });
  it("Should compare a string of length six with another which is not a permutation of the former", () => {
    let str1 = "abcdef";
    let str2 = "abcdff";
    expect(isPermutation(str1, str2)).toBeFalsy();
  });
});
